/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateDCA } from "./PrivateDCA";
export * as factories from "./factories";
export { PrivateDCA__factory } from "./factories/PrivateDCA__factory";
